# Generated by Django 4.2.1 on 2023-12-18 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_label', models.CharField(max_length=255)),
                ('calories', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('image_url', models.URLField()),
                ('website_url', models.URLField()),
                ('ingredient_lines', models.TextField()),
                ('summary', models.TextField()),
                ('cuisine_type', models.CharField(max_length=100)),
                ('time_in_minutes', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
