# Generated by Django 4.2.1 on 2023-12-18 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customuser_email_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='category',
        ),
        migrations.RemoveField(
            model_name='favorites',
            name='cuisine_type',
        ),
        migrations.RemoveField(
            model_name='favorites',
            name='ingredient_lines',
        ),
        migrations.RemoveField(
            model_name='favorites',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='favorites',
            name='time_in_minutes',
        ),
        migrations.RemoveField(
            model_name='favorites',
            name='website_url',
        ),
    ]
