# Generated by Django 4.2.1 on 2024-01-12 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_folder_folders_rename_recipe_recipes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='folder',
        ),
        migrations.AddField(
            model_name='folders',
            name='recipes',
            field=models.ManyToManyField(related_name='folders', to='api.recipes'),
        ),
    ]
