# Generated by Django 4.2.1 on 2024-01-13 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_recipes_folder_folders_recipes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorites',
            options={'verbose_name_plural': 'Favorites'},
        ),
        migrations.AlterModelOptions(
            name='folders',
            options={'verbose_name_plural': 'Folders'},
        ),
        migrations.AlterModelOptions(
            name='recipes',
            options={'verbose_name_plural': 'Recipes'},
        ),
    ]
