# Generated by Django 4.2.3 on 2024-02-23 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_mealplan_mealdates'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealdates',
            name='event_id',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
