# Generated by Django 4.2.1 on 2023-12-18 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_favorites_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='calories',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
