# Generated by Django 4.2.1 on 2023-12-18 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_favorites_image_url_alter_favorites_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='calories',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
