# Generated by Django 4.2.1 on 2023-12-22 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_favorites_calories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorites',
            options={'verbose_name_plural': 'Favorites'},
        ),
    ]
