# Generated by Django 4.2.3 on 2024-02-23 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_mealdates_event_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealdates',
            old_name='event_id',
            new_name='eventID',
        ),
    ]
