# Generated by Django 4.2.1 on 2023-12-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_favorites_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='image_url',
            field=models.URLField(default='https://example.com/default_image.jpg'),
        ),
        migrations.AddField(
            model_name='favorites',
            name='website_url',
            field=models.URLField(default='https://google.com'),
        ),
    ]
