# Generated by Django 4.2.1 on 2023-12-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_favorites_image_url_favorites_website_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='category',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='favorites',
            name='cuisine_type',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='favorites',
            name='ingredient_lines',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='favorites',
            name='summary',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='favorites',
            name='time_in_minutes',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='image_url',
            field=models.URLField(default='https://example.com/default_image.jpg', max_length=2000),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='website_url',
            field=models.URLField(default='https://google.com', max_length=2000),
        ),
    ]
