# Generated by Django 4.2.1 on 2023-12-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_favorites_category_favorites_cuisine_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='time_in_minutes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
