# Generated by Django 4.2.3 on 2023-12-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_favorites_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='category',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
