# Generated by Django 4.2.1 on 2023-12-23 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_favorites_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorites',
            old_name='category',
            new_name='meal_type',
        ),
    ]
