# Generated by Django 4.2.1 on 2023-12-23 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_category_favorites_meal_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='meal_type',
        ),
    ]
