# Generated by Django 4.2.1 on 2023-12-23 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_favorites_meal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='category',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='favorites',
            name='meal_type',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
