# Generated by Django 4.2.1 on 2023-12-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_favorites_category_favorites_meal_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='category',
        ),
        migrations.AlterField(
            model_name='favorites',
            name='cuisine_type',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
