# Generated by Django 4.2.1 on 2023-12-23 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_favorites_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='meal_type',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
